version: '3'
services:
  php-app:
    image: image_momo
    depends_on:
      - rabbitmq
  web:
    build:
      context: . C:\Users\VotreNom\Documents\Docker\php-app:/var/www/html
      dockerfile: Dockerfile 
    ports:
      - "8080:80" # Redirige le port 8080 de l'hôte vers le port 80 du conteneur
    volumes:
      - ./client.php:/var/www/html/client.php
      - ./server.php:/var/www/html/server.php
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # Accès au gestionnaire RabbitMQ
      - "5672:5672" # Port de communication standard RabbitMQ
